/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author User
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        MenuCadastrar = new javax.swing.JMenu();
        jMenuCadEmpresa = new javax.swing.JMenuItem();
        jMenuCadFuncionario = new javax.swing.JMenuItem();
        jMenuCadHolerite = new javax.swing.JMenuItem();
        jMenuholerite = new javax.swing.JMenu();
        MenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuCadastrar.setText("Cadastrar ");

        jMenuCadEmpresa.setText("Empresa");
        jMenuCadEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadEmpresaActionPerformed(evt);
            }
        });
        MenuCadastrar.add(jMenuCadEmpresa);

        jMenuCadFuncionario.setText("Funcionario");
        jMenuCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadFuncionarioActionPerformed(evt);
            }
        });
        MenuCadastrar.add(jMenuCadFuncionario);

        jMenuCadHolerite.setText("Holerite");
        jMenuCadHolerite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCadHoleriteActionPerformed(evt);
            }
        });
        MenuCadastrar.add(jMenuCadHolerite);

        jMenuBar2.add(MenuCadastrar);

        jMenuholerite.setText("Holerite");
        jMenuholerite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuholeriteMouseClicked(evt);
            }
        });
        jMenuholerite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuholeriteActionPerformed(evt);
            }
        });
        jMenuBar2.add(jMenuholerite);

        MenuSair.setText("Sair");
        MenuSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuSairMouseClicked(evt);
            }
        });
        MenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSairActionPerformed(evt);
            }
        });
        jMenuBar2.add(MenuSair);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 514, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 351, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuCadEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadEmpresaActionPerformed
        // TODO add your handling code here:
         CadEmpresa cadastraempresa = new CadEmpresa();
         cadastraempresa.setVisible(true);
          dispose();
    }//GEN-LAST:event_jMenuCadEmpresaActionPerformed

    private void jMenuCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadFuncionarioActionPerformed
        // TODO add your handling code here:
        CadFuncionario cadastrafuncionario = new CadFuncionario();
         cadastrafuncionario.setVisible(true);
          dispose();
    }//GEN-LAST:event_jMenuCadFuncionarioActionPerformed

    private void jMenuCadHoleriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuCadHoleriteActionPerformed
        // TODO add your handling code here:
       Holerite holerite = new Holerite();
       holerite.setVisible(true);
       dispose();
       
    }//GEN-LAST:event_jMenuCadHoleriteActionPerformed

    private void jMenuholeriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuholeriteActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuholeriteActionPerformed

    private void MenuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSairActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_MenuSairActionPerformed

    private void MenuSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuSairMouseClicked
        // TODO add your handling code here:
          System.exit(0);
    }//GEN-LAST:event_MenuSairMouseClicked

    private void jMenuholeriteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuholeriteMouseClicked
        // TODO add your handling code here:
        Imprimir pesquisa = new Imprimir();
        pesquisa.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuholeriteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuCadastrar;
    private javax.swing.JMenu MenuSair;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuCadEmpresa;
    private javax.swing.JMenuItem jMenuCadFuncionario;
    private javax.swing.JMenuItem jMenuCadHolerite;
    private javax.swing.JMenu jMenuholerite;
    // End of variables declaration//GEN-END:variables
}
